### ISSUE TITLE
ATS9870 issues

### ISSUE THREAD

**Issue by damazter** [microsoft/Qcodes#122]
Here I copied the remaining issues of pull request #66 

1

> can you make a docstring describing what form coupling, channel_range, impedance, and bwlimit should have?
> And if there's a docstring, the whole first part of this method (and acquire too) could be rewritten:
> 
> ```
> def config(self, **kwargs):
>     for k, v in kwargs.items():
>         if isinstance(v, (list, tuple)):
>             for i, vi in enumerate(v):
>                 self.parameters[k + str(i + 1)]._set(vi)
>         else:
>             self.parameters[k]._set(v)
> ```

2

> not a big deal, but I much prefer implied continuation from parentheses instead of backslashes

3

> success (spelling mistake in our variable)

4

> this pattern:
> 
> ``` python
> return_code = self._ATS9870_dll.Alazarxxxxx(self._handle, ...)
> self._result_handler(error_code=return_code, error_source='Alazarxxxxx')
> ```
> 
> gets a little tedious. What about something like this instead of _result_handler:
> 
> ``` python
> def call_dll(self, func_name, *args):
>     func = getattr(self._ATS9870_dll, func_name)
>     return_code = func(self._handle, *args)
>     if error_code != self._success:
>         # TODO (C) log error
>         # include the args (the beginning anyway) so you don't need the special case
>         # of one or more args in the error_source, and you get more info to debug with
>         argrepr = repr(args)
>         if len(argrepr) > 100:
>             argrepr = argrepr[:96] + '...)'
>         # put error_code in a class attribute so we're not constantly re-evaluating the dict
>         if error_code not in self._error_codes:
>             raise KeyError('unknown error {} from function {} with args: {}'.format(
>                 error_code, func_name, argrepr))
>         raise Exception('error {}: {} from function {} with args: {}'.format(
>             error_code, self._error_codes[error_code], func_name, argrepr))
> ```
> 
> I could even imagine including a kwarg updates=['clock_source', 'sample_rate', 'clock_edge', 'decimation'] that would create the _set_updated() calls that also consistently trail this pattern.
> Also, it's maybe a matter of style, but I wouldn't call the unknown error a KeyError because the error itself isn't that the key is missing, that's just the reason you don't have more info to give the user about it. I'd probably call them both RuntimeError

**Comment by WilliamHPNielsen** [comment]
@jenshnielsen, is this issue still relevant?

**Comment by astafan8** [comment]
no, that part of the alazar driver code is different now and follows the `_call_dll` suggestion.
